// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL7P-W2oX9YqArRKhRTeSC18RKXDlmzGE',
    appId: '1:404596333772:web:954f319660e749ad657669',
    messagingSenderId: '404596333772',
    projectId: 'e6piccturenew',
    authDomain: 'e6piccturenew.firebaseapp.com',
    storageBucket: 'e6piccturenew.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAap6cT0TDYE7xn8SOWgPux23VPNjVQbkg',
    appId: '1:404596333772:android:b84aefa62a06f602657669',
    messagingSenderId: '404596333772',
    projectId: 'e6piccturenew',
    storageBucket: 'e6piccturenew.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn7Z1AJ42aRImK8iNTJNW1OpVidk5BPec',
    appId: '1:404596333772:ios:3a2293703f664333657669',
    messagingSenderId: '404596333772',
    projectId: 'e6piccturenew',
    storageBucket: 'e6piccturenew.firebasestorage.app',
    iosBundleId: 'com.example.e6piccturenew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn7Z1AJ42aRImK8iNTJNW1OpVidk5BPec',
    appId: '1:404596333772:ios:3a2293703f664333657669',
    messagingSenderId: '404596333772',
    projectId: 'e6piccturenew',
    storageBucket: 'e6piccturenew.firebasestorage.app',
    iosBundleId: 'com.example.e6piccturenew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL7P-W2oX9YqArRKhRTeSC18RKXDlmzGE',
    appId: '1:404596333772:web:757e77a20568f5f0657669',
    messagingSenderId: '404596333772',
    projectId: 'e6piccturenew',
    authDomain: 'e6piccturenew.firebaseapp.com',
    storageBucket: 'e6piccturenew.firebasestorage.app',
  );
}
